### ISSUE TITLE
Using FinaleMe with  other references and organisms - where to get reference files

### ISSUE THREAD

**Issue by danarte** [epifluidlab/FinaleMe#1]
Hello,
Thanks for sharing your code, it's an amazing resource for researchers from this field.
I have a question regarding the usage of this tool for other references like hg38.
Also, I have a project involving genomic data from mice, is there a possibility to use this tool for mouse data?

After a brief inspection it came down to those files, for which I couldn't find any source online:
CpgMultiMetricsStats.hg19.details.bed.gz
wgbs_buffyCoat_jensen2015GB.methy.hg19.bw
wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed
autosome_1kb_intervals.UCSC.cpgIsland_plus_shore.b37.bed output.add_value.methy.bed.gz 

Is there any chance you have those files for hg38 and mm10? Or could you provide instructions on how one could obtain those files?

Thanks.

**Comment by dnaase** [comment]
for CpgMultiMetricsStats.hg19.details.bed.gz , you can generate in "Step 1: extract features from bam files for the training and decoding"
for wgbs_buffyCoat_jensen2015GB.methy.hg19.bw, i did not have hg38 in hand, but you can generate it by using the fastq files (buffycoat) from jensen et al. 2015 Genome Biology. Or anyother buffycoat WGBS data from healthy individuals.
for wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed, this is a blacklist file, you can download it from TableBrowser in UCSC, basically to exclude any dark region in the reference genome
for autosome_1kb_intervals.UCSC.cpgIsland_plus_shore.b37.bed., this is a CpG island+shore (+/-2kb around CpG island), and then you can split it into 1kb regions by bedtools

**Comment by liujilei156231** [comment]
We thank the team of authors for providing the open source code. However, more and more researchers are using hg38, so updating the tutorial to the hg38 version is beneficial to the research community. Looking forward to the update!
