### ISSUE TITLE
How can I know the methylation status from each cfDNA fragment

### ISSUE THREAD

**Issue by wangxincer** [epifluidlab/FinaleMe#11]
I have completed steps 1 to 4 and  obtained a file named 'test.FinaleMe.mincg7.prediction.bed.gz'. This file contains the predicted methylation levels for each CpG site in the ref genome. How can I determine the methylation status of each CpG site within a specific fragment?

**Comment by dnaase** [comment]
Since the file size is very big, we only provide the aggregated prediction results at CpG position.
