### ISSUE TITLE
Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is smaller than, or equal to, the minimum (0)

### ISSUE THREAD

**Issue by LauraAndersen** [epifluidlab/FinaleMe#3]
Hi

I'm trying to run your code, however I run into an error in step 2 of your tutorial:

`Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is smaller than, or equal to, the minimum (0)
	at org.apache.commons.math3.distribution.fitting.MultivariateNormalMixtureExpectationMaximization.estimate(MultivariateNormalMixtureExpectationMaximization.java:308)
	at org.cchmc.epifluidlab.finaleme.hmm.ClustersGMM.<init>(GMMLearner.java:346)
	at org.cchmc.epifluidlab.finaleme.hmm.GMMLearner.<init>(GMMLearner.java:87)
	at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.buildInitNhmmByGMM(FinaleMe.java:1414)
	at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.trainHmm(FinaleMe.java:802)
	at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.doMain(FinaleMe.java:236)
	at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.main(FinaleMe.java:170)`

I run it with the following command:

`java -Xmx100G -cp "target/FinaleMe-0.58-jar-with-dependencies.jar:lib/jahmm-0.6.2.jar" org.cchmc.epifluidlab.finaleme.hmm.FinaleMe test.FinaleMe.mincg7.model CpgMultiMetricsStats.hg19.details.bed.gz test.FinaleMe.mincg7.prediction.bed.gz -miniDataPoints 7 -gmm -covOutlier 3`

and with the files provided in the tutorial wgbs_buffyCoat_jensen2015GB.methy.hg19.bw，wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed，hg19.2bit， hg19.chrom.size and cpgIslandExt.txt.gz downloaded from http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/. I use the chr22 bam file you provided for testing.

Can you please help me?

Thanks!

**Comment by dnaase** [comment]
how did you generate the "CpgMultiMetricsStats.hg19.details.bed.gz"? it looks like some of the features are not positive (e.g., fragment length, coverage, or distance to the center of fragment ). Could you please check the input files?

**Comment by LauraAndersen** [comment]
Thanks for getting back to me. I generated the "CpgMultiMetricsStats.hg19.details.bed.gz" using step 1 of your tutorial:

`java -Xmx20G -cp "target/FinaleMe-0.58-jar-with-dependencies.jar:lib/gatk-package-distribution-3.3.jar:lib/sis-jhdf5-batteries_included.jar:lib/java-genomics-io.jar:lib/igv.jar" org.cchmc.epifluidlab.finaleme.utils.CpgMultiMetricsStats extdata/hg19.2bit extdata/CG_motif.hg19.common_chr.pos_only.bedgraph extdata/CG_motif.hg19.common_chr.pos_only.bedgraph extdata/output.bam CpgMultiMetricsStats.hg19.details.bed.gz -stringentPaired -excludeRegions extdata/wgEncodeDukeMapabilityRegionsExcludable_wgEncodeDacMapabilityConsensusExcludable.hg19.bed -valueWigs methyPrior:0:extdata/wgbs_buffyCoat_jensen2015GB.methy.hg19.bw -wgsMode`

where the 'CG_motif.hg19.common_chr.pos_only.bedgraph' file is a bed file with chr, start, end and then a column with the number 1.

I've attached the file I use for step 2 input:

[CpgMultiMetricsStats.hg19.details.bed.gz](https://github.com/epifluidlab/FinaleMe/files/14825351/CpgMultiMetricsStats.hg19.details.bed.gz)

Thanks!

**Comment by dnaase** [comment]
For unknown reason, in the following two rows, the offset_frag (10th column) is smaller than Dist_frag_end (11th column). can you try to delete these two rows first and see if it works?

chr22	47054031	47054274	1328848458	177	-	m	7.849820	33	79	98	95.818
chr22	47054031	47054274	1328848447	120	-	m	7.849820	33	37	83	95.818

**Comment by LauraAndersen** [comment]
It gives me the same error message. It's like something goes wrong when loading 'offset' in line 574 of FinaleMe.java. The length here is 1 for all of the reads which means it never enters the loop in line 567. I've attached the CpG motif file that I use if that's any help. 
[CG_motif.hg19.common_chr.pos_only.bedgraph.txt](https://github.com/epifluidlab/FinaleMe/files/14837480/CG_motif.hg19.common_chr.pos_only.bedgraph.txt)
thanks!

**Comment by robinycfang** [comment]
Is there any update on this issue? I encountered the same error

**Comment by pei-wang111** [comment]
Has there been a solution to this issue? I'm encountering the same problem.

**Comment by pei-wang111** [comment]
Exception in thread "main" org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is
        at org.apache.commons.math3.distribution.fitting.MultivariateNormalMixtureExpectationMaxiaximization.java:308)
        at org.cchmc.epifluidlab.finaleme.hmm.ClustersGMM.<init>(GMMLearner.java:346)
        at org.cchmc.epifluidlab.finaleme.hmm.GMMLearner.<init>(GMMLearner.java:87)
        at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.buildInitNhmmByGMM(FinaleMe.java:1403)
        at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.trainHmm(FinaleMe.java:791)
        at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.doMain(FinaleMe.java:236)
        at org.cchmc.epifluidlab.finaleme.hmm.FinaleMe.main(FinaleMe.java:170)

**Comment by heweihuang** [comment]
> 有没有解决这个问题的方法？我遇到了同样的问题。

+1

**Comment by elicj01** [comment]
Hi, 
I initially used the CpG coordinates for CpG islands from this file: [cpgIslandExt.txt.gz](https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cpgIslandExt.txt.gz). I think that using this file may be why I've encountered this error. I then switched to use a file that contains the coordinates for the CpG sites (i.e. the CG dinucleotides within the CpG island regions), and I was able to successfully complete step 2 and step 3.

I hope this is the right approach and that it helps you all!

**Comment by peterhunyadi** [comment]
Thank you very much @elicj01 , that made it work finally!
In hindsight that makes a lot of sense, as that is what the description in the readme let's us believe, but I also got sidetracked by the CpGisland file that was mentioned in a couple posts here.

Once again, cheers!

**Comment by wangxincer** [comment]
> Hi, I initially used the CpG coordinates for CpG islands from this file: https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cpgIslandExt.txt.gz I think that using this file may be why I've encountered this error. I then switched to use a file that contains the coordinates for the CpG sites (i.e. the CG dinucleotides within the CpG island regions), and I was able to successfully complete step 2 and step 3.
> 
> I hope this is the right approach and that it helps you all!

Hi, I've encountered the same error with different CpG island files. Could you please provide a valid CpG island file? Thank you!

**Comment by elicj01** [comment]
> > Hi, I initially used the CpG coordinates for CpG islands from this file: https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cpgIslandExt.txt.gz I think that using this file may be why I've encountered this error. I then switched to use a file that contains the coordinates for the CpG sites (i.e. the CG dinucleotides within the CpG island regions), and I was able to successfully complete step 2 and step 3.
> > I hope this is the right approach and that it helps you all!
> 
> Hi, I've encountered the same error with different CpG island files. Could you please provide a valid CpG island file? Thank you!

I tested it with different CpG files. One that I used is this one [CpG_coordsEPICv2.txt](https://github.com/user-attachments/files/17231502/CpG_coordsEPICv2.txt). This file contains the CpGs on chromosome 22 that are part of the Infinium MethylationEPIC v2.0 Illumina Kit. You can download the original Illumina file from their website and filter it to extract the relevant columns (chromosome, start, end, then adding a 4th column with 1s to create the .bedgraph) for the different CpGs. 

Alternatively you can repeat this proccess using the CpG file from Infinium HumanMethylation450 BeadChip to get another CpG coordinates file with other CpGs

**Comment by wangxincer** [comment]
> > > Hi, I initially used the CpG coordinates for CpG islands from this file: https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cpgIslandExt.txt.gz I think that using this file may be why I've encountered this error. I then switched to use a file that contains the coordinates for the CpG sites (i.e. the CG dinucleotides within the CpG island regions), and I was able to successfully complete step 2 and step 3.
> > > I hope this is the right approach and that it helps you all!
> > 
> > 
> > Hi, I've encountered the same error with different CpG island files. Could you please provide a valid CpG island file? Thank you!
> 
> I tested it with different CpG files. One that I used is this one [CpG_coordsEPICv2.txt](https://github.com/user-attachments/files/17231502/CpG_coordsEPICv2.txt). This file contains the CpGs on chromosome 22 that are part of the Infinium MethylationEPIC v2.0 Illumina Kit. You can download the original Illumina file from their website and filter it to extract the relevant columns (chromosome, start, end, then adding a 4th column with 1s to create the .bedgraph) for the different CpGs.
> 
> Alternatively you can repeat this proccess using the CpG file from Infinium HumanMethylation450 BeadChip to get another CpG coordinates file with other CpGs

Thank you very much!! It works for step1- step4!

**Comment by dnaase** [comment]
apologize about the delayed responses. I uploaded the cpg bedgraph files i used in the newest zenodo.org:
[CG_motif.hg19.common_chr.pos_only.bedgraph.gz](https://zenodo.org/records/14013719/files/CG_motif.hg19.common_chr.pos_only.bedgraph.gz?download=1)
